name: php-cron
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: curl
      - run: php script.php
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: scheduled php output"
